<a href="https://colab.research.google.com/github/egitonga395/kamilimu_assignments/blob/erick_statistical_analysis/erick_statistical_analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Section 1

##Question 1
In inferential statistics, we attempt to draw a conclusion about a population from sample data. Define the two terms:

a. sample

b. population

A sample is a portion represenating part of a population of data under study

Population  is the complete set of data under study

##Question 2
When we estimate an unknown population value using a confidence interval, what does the confidence interval tell us?

The confidence interval gives a range under which the estimate being investigated falls into. This means that there is a higher probability of the estimate value to be within the range of value.

##Question 3
3. What is a hypothesis?

A hypothesis is a statement used in statistics to state a claim or fact about a sample/population

##Question 4
Describe the two types of hypothesis. Give an example for each.

Null hypothesis e.g The mean age of KamiLimu cohort 9 is 21

Alternative hypothesis e.g The mean age of KamiLimu 9 is not 21

##Question 5
5. What is hypothesis testing? Which of the two types of hypothesis do we test in hypothesis testing?

Hypothesis testing is a method of testing the null hypothesis to see whether to reject or hold the null hypothesis


1.  z-statistic
2.  t-statistic

##QUESTION 6
6. Describe the step-by-step process for hypothesis testing.

State the null and alternative hypotheses

Choose a a significance level which is alpha

Conduct the statistical test

compute a test statistic

calculate the P-value

Make a decision if the p-value is greater than the significance value then

##QUESTION 7
7. What is alpha in hypothesis testing?

Alpha is the significance level.
Alpha is a probability of rejecting the null hypothesis. (1- alpha ) is called confidence level and is the opposite. It is a value that is used to make a decision over a null hypothesis. It test the significance of the p-value by evaluating whether it is greater or less. If the significance value is greater than the P value we reject the null hypothesis else we accept. The significance level is a measure of risk that a researcher is willing to take in case their decision of rejecting the null hypothesis is wrong. This error is what is called Type I error.

##QUESTION 8
8. How does the p-value obtained from hypothesis testing relate to alpha?

The P-value is the probability of getting the results if the null hypothesis is true. The value is compared to the significance level to determine whether to reject or accept the hypothesis. In the p-value value approach, we compare propability/areas against the critical region. For a left-tailed test if the P-value is less the than the critical value the null hypothesis is rejecting .

#QUESTION 9
9. When selecting which statistical test to use in hypothesis testing, what assumptions do we make about the data for a parametric test?

The data is normally distributed.
The datapoints have equal variances

#QUESTION 10
10. Name one test used to determine whether a datset is a normal distribution.

Shapiro walk test

#SECTION II

Are male and female olympic athletes the same height on average?

Testing using a significance level of alpha = 0.05

Null hypothesis: the average height of male =  average height of females
Alternative hypothesis: The average height of male != average height of females

b. We have already chosen the significance level of (α = 0.05). So the next step is to choose the appropriate statistical test: consider whether the data is numerical or categorical, whether the groups are independent, and the number of groups. Also test for normality of the data as well as equality of variance.

c. State the justifications for your choice for a statistical test.

d. Prepare the data. Handle missing values and filter for male and female athletes with valid height entries.

e. Conduct the statistical test.

f. Compute the test statistic and p-value.

g. Make a decision: interpret the p-value and state whether you reject or fail to reject the null hypothesis.

The data is numerical. The groups(male and female) are independent of each others height. There are two groups.

Test for normality Ks (Kolmogorov-Smirnov) normality test beacause data points are about 50

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
athletes = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/athlete_events.csv")
df = athletes[['Height', "Sex"]].dropna()
df.head()

   Height Sex
0   180.0   M
1   170.0   M
4   185.0   F
5   185.0   F
6   185.0   F

In the KS test we make the null hypothesis that the data is normally distributed and we compare it to the theoretical normal distribution.

In [ ]:

height_female = df[df["Sex"] == "F"]["Height"]
height_male = df[df["Sex"] == "M"]["Height"]
height_male.head()

0     180.0
1     170.0
10    188.0
11    188.0
12    188.0
Name: Height, dtype: float64

In [ ]:
from scipy import stats
normal_ditribution_analysis = stats.ks_2samp(height_female, height_male)
print(normal_ditribution_analysis)

KstestResult(statistic=np.float64(0.4692458799580993), pvalue=np.float64(0.0), statistic_location=np.float64(173.0), statistic_sign=np.int8(1))

We therefore reject that null hypothesis that the data was obtained from a normal dataset.

Equality of variance

In [ ]:
equality_of_variance = stats.bartlett(height_female, height_male)
equality_of_variance

BartlettResult(statistic=np.float64(371.6710077863091), pvalue=np.float64(8.097782392473336e-83))

State the justifications for your choice for a statistical test.

1. The Kolmogorov-Smirnov (KS) is normality test that calculates to see whether the data has been obtained from a normally ditributed data. It can check for a one sample of data in a population. It can also to check for two sample of data. it produces a p-value which should be validated with signficance level(alpha).The null hypothesis that holds at in the KS test is that the data is from a normally distributed dataset. If the value is less than the significance valBartletta thee we reject the null hypothesis
2. The bartlett is look for the equivalence of variance. This check whether the sample being tensted has the same variance all across the population

Conduct the statistical test.

In [ ]:
mean_statistical_test = stats.ttest_ind(height_female, height_male, equal_var=True)
stats = mean_statistical_test.statistic
p_value = mean_statistical_test.pvalue
print(stats)
print(p_value)

TtestResult(statistic=np.float64(-257.0759194444727), pvalue=np.float64(0.0), df=np.float64(210943.0))

Since the p-value is less than the significance value this means  that we reject the null hypothesis; height of the male athletes and female athletes  is not equal. We therefore adopt the alternative hypothesis.